# Generated by Django 5.2 on 2025-05-15 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_usuario_professor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservar_de_ambiente',
            name='professor_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='professor_disciplina',
            field=models.ForeignKey(limit_choices_to={'is_professor': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
